'use strict';


module.exports.firstPlan = {
  name: 'my first plan',
  meals: [{
    meal_order: 11,
    weekday: 'monday',
    meal_type: 'breakfast',
    recipe_id: null
  }, {
    meal_order: 21,
    weekday: 'tuesday',
    meal_type: 'breakfast',
    recipe_id: null
  }, {
    meal_order: 31,
    weekday: 'wednesday',
    meal_type: 'breakfast',
    recipe_id: null
  }, {
    meal_order: 41,
    weekday: 'thursday',
    meal_type: 'breakfast',
    recipe_id: null
  }, {
    meal_order: 51,
    weekday: 'friday',
    meal_type: 'breakfast',
    recipe_id: null
  }, {
    meal_order: 61,
    weekday: 'saturday',
    meal_type: 'breakfast',
    recipe_id: null
  }, {
    meal_order: 71,
    weekday: 'sunday',
    meal_type: 'breakfast',
    recipe_id: null
  }, {
    meal_order: 12,
    weekday: 'monday',
    meal_type: 'lunch',
    recipe_id: null
  }, {
    meal_order: 22,
    weekday: 'tuesday',
    meal_type: 'lunch',
    recipe_id: null
  }, {
    meal_order: 32,
    weekday: 'wednesday',
    meal_type: 'lunch',
    recipe_id: null
  }, {
    meal_order: 42,
    weekday: 'thursday',
    meal_type: 'lunch',
    recipe_id: null
  }, {
    meal_order: 52,
    weekday: 'friday',
    meal_type: 'lunch',
    recipe_id: null
  }, {
    meal_order: 62,
    weekday: 'saturday',
    meal_type: 'lunch',
    recipe_id: null
  }, {
    meal_order: 72,
    weekday: 'sunday',
    meal_type: 'lunch',
    recipe_id: null
  }, {
    meal_order: 13,
    weekday: 'monday',
    meal_type: 'dinner',
    recipe_id: null
  }, {
    meal_order: 23,
    weekday: 'tuesday',
    meal_type: 'dinner',
    recipe_id: null
  }, {
    meal_order: 33,
    weekday: 'wednesday',
    meal_type: 'dinner',
    recipe_id: null
  }, {
    meal_order: 43,
    weekday: 'thursday',
    meal_type: 'dinner',
    recipe_id: null
  }, {
    meal_order: 53,
    weekday: 'friday',
    meal_type: 'dinner',
    recipe_id: null
  }, {
    meal_order: 63,
    weekday: 'saturday',
    meal_type: 'dinner',
    recipe_id: null
  }, {
    meal_order: 73,
    weekday: 'sunday',
    meal_type: 'dinner',
    recipe_id: null
  }]
};